project:
  type: book
  output-dir: ../docs
  resources: "./fonts/"


execute:
  output: asis
  echo: false

book:  
  language: de
  title: "Ein Gemäldekatalog"
  author: "CPS"
  date: today
  chapters:
    - index.qmd
    - section1.qmd
    - section3.qmd
    - impressum.qmd
  downloads: [pdf, epub, docx]
  page-footer: |
    Eine CPS-Demo, die mit CbDD Open Data erstellt wurde.

    [Datenschutzerklärung](https://www.tib.eu/de/datenschutz)
  repo-url: https://github.com/calnfynn/wb2jn_demo
  repo-actions: [source, issue]



bibliography: references.bib

format:
  html:
    toc: true
    toc-title: "Inhaltsverzeichnis"
    toc-depth: 5
    lightbox: true
    number-sections: false
    theme: ./webstyle.scss

    
  pdf:
    documentclass: scrreprt
        # FOR TITLE PAGE
    title-bg: "./b648f36e1efedcd91e59a0585194b9ae8783dbbfae9257bdc1d00e4b0c3e5bb7.jpeg"
    titlepage: false
    template-partials:
      - "before-body.tex"
    include-in-header: in-header.tex
    include-after-body: 
      text: |
        \printindex
    number-sections: false
    papersize: a4
    geometry:
      - top=30mm
      - left=10mm
      - right=10mm
      - heightrounded
    toc-title: "Inhaltsverzeichnis"
    linkcolor: darkred
    filecolor: darkred
    urlcolor: darkred
    toc-color: black

  epub: 
    toc-title: "Inhaltsverzeichnis"
    number-sections: false
    css: fonts.css
    theme: epubstyle.scss
    embed-resources: true
    epub-fonts:
      - fonts/Figtree-Regular.ttf
      - fonts/Figtree-Italic.ttf
      - fonts/Figtree-Bold.ttf
      - fonts/Figtree-BoldItalic.ttf
      - fonts/NotoSerif-Regular.ttf
      - fonts/NotoSerif-Italic.ttf
      - fonts/NotoSerif-Bold.ttf
      - fonts/NotoSerif-BoldItalic.ttf
    epub-cover-image: epubcover.jpg
    fig-cap-location: bottom
    
  docx:
    number-sections: false

