project:
  type: book
  output-dir: ../docs

execute:
  output: asis
  echo: false

book:  
  language: de
  title: "Ein Gemäldekatalog"
  author: "CPS"
  date: today
  chapters:
    - index.qmd
#    - section0.qmd
    - section1.qmd
#    - section2.qmd
    - section3.qmd
  downloads: [pdf, epub, docx]

bibliography: references.bib

format:
  html:
    #theme:
    #  dark: solar
    #  light: morph
    toc: true
    toc-depth: 5
    lightbox: true
    number-sections: false


    
  pdf:
    documentclass: scrreprt
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
        \let\oldincludegraphics\includegraphics
        \renewcommand{\includegraphics}[2][]{%
          \oldincludegraphics[width=\linewidth,height=0.70\textheight,keepaspectratio,#1]{#2}%
        }
    include-after-body: 
      text: |
        \printindex
    pdf-engine: pdflatex
    number-sections: false
    papersize: a4
  epub: 
    number-sections: false
  docx: 
    number-sections: false

